# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraftVersion=26.1.2
loaderVersion=0.19.3
loomVersion=1.17-SNAPSHOT
fabricKotlinVersion=1.13.13+kotlin.2.4.10

# Dependencies
fabricApiVersion=0.155.2+26.1.2
